### ISSUE TITLE
doesn't work !

### ISSUE THREAD

**Issue by PuriaRad** [sidrai97/currency-converter-api#1]
I tried many different requests and even the example ,but none of them worked.

**Comment by sidrai97** [comment]
Thanks, @PuriaRad the service I was scraping changed their URL so that's why it wasn't working. Anywayz I have fixed it now, you can check it out [here](https://currency-converter-api97.herokuapp.com/api?a=1&f=btc&t=inr) with the correct codes mentioned in the documentation.
